# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ""
tagline:          ''
description:      ''
url:              "http://jliggett.github.io"
baseurl:          ''

author:
  name:           "@jlliggett"
  url:            https://twitter.com/jlliggett

plugins:
paginate: 


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jliggett/jliggett.github.io
