# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ifykwis
tagline:          'perhaps you know what I am trying to say'
description:      ''
url:              http://ifykwis.com
baseurl:          /

author:
  name:           'Jason Liggett'
  url:            https://twitter.com/jlliggett

paginate:         5


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jliggett/jliggett.github.io