# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ifykwis
tagline:          'perhaps you know what I am trying to say'
description:      ''
url:              http://jliggett.github.io
baseurl:          /

author:
  name:           'Jason Liggett'
  url:            https://twitter.com/jlliggett

plugins:
  - jekyll-paginate
paginate: 5


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/jliggett/jliggett.github.io
